#!/usr/bin/env bash
# Why you don't love me?
termfunc() {
	rm /var/run/myscript.pid
	exit
}

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command" && termfunc' SIGTERM
trap 'termfunc' SIGQUIT

myPID = $$
echo " $myPID" > /var/run/myscript.pid

while [ true ];
do
    echo "To infinity and beyond"
    sleep 2
done

