#!/usr/bin/env bash
# work with deamons
PROCESS_NAME="manage_my_process"
PROCESS_EXEC="./manage_my_process"
PID_FILE="/var/run/my_process.pid"

create()
{
    sudo touch $FILE
    sudo bash -c "echo $$ > $FILE"
}

start_process() {
     create
    ./manage_my_process &
    echo "manage_my_process started"
}

stop_process() {
    [ -e "/var/run/my_process.pid" ] && sudo pkill -f "./manage_my_process" && rm /var/run/my_process.pid
    echo "manage_my_process stopped"
}

restart_process() {
    $0 stop >& /dev/null
    $0 start >& /dev/null
    echo "manage_my_process restarted"
}

usage() {
    echo "Usage: $0 {start|stop|restart}"
    exit 1
}

if [ $# -ne 1 ]; then
    usage
fi

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        usage
        ;;
esac

exit 0