#!/usr/bin/env bash
# read etc/passwd.

while IFS=: read -r username _ userid _ _ home shell; 
do    
    echo "The user $username is part of the $userid gang, lives in $home and rides $shell."
done < /etc/passwd
